# This theme is based on https://github.com/jekyll/minima
# Please refer above link to know the available configurations

title: "NagroMS - Networked Agro Management System"
remote_theme: cepdnaclk/eYY-project-theme
description: "Empowering Sri Lankan Agriculture through Direct Marketplace and Community Network"
markdown: kramdown

kramdown:
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: false
